### ISSUE TITLE
link to more useful/specific doc for configuring transport

### ISSUE THREAD

**Issue by psugihara** [successor-software/mailing#44]
<img width="376" alt="Screen Shot 2022-07-21 at 9 40 33 AM" src="https://user-images.githubusercontent.com/282016/180268038-18d9eeda-096c-4918-9742-a52aa472328c.png">
 

@alexfarrill you mentioned this the other day. I think it's a good idea, wanted to capture.

**Comment by alexfarrill** [comment]
Added an anchor tag to the README section we already had about transport and a linked to it in PreviewSender

**Comment by psugihara** [comment]
nice!
