### ISSUE TITLE
Unable to send email from Next.js API route in production

### ISSUE THREAD

**Issue by neuxregime** [successor-software/mailing#72]
Hey there! I've been exploring mailing for the past two days and everything was going great until decided to test some production scenarios. Put simply, everything works as long as preview server is running: templates are compiled, and emails are successfully sent via sendgrid. 

However, as soon as I stop the preview server to test actual functionality, I start running into issues, primarily emails are not sent at all. I get the following error in my terminal
![image](https://user-images.githubusercontent.com/89808147/182475418-499080a2-c138-4737-9c08-509d6b2733e8.png)

The code I use in my next.js API route is
```typescript
import { sendMail } from '~/emails';

...

      const t = await sendMail({
        subject: `Ready for 123?`,
        to: entry.email,
        component: React.createElement(RSVPEmail, {
          entry,
        }),
      });
      console.log(t);
```

`emails/index.ts` is
```typescript
import nodemailer from 'nodemailer';
import { buildSendMail } from 'mailing-core';
import dotenv from 'dotenv';

dotenv.config({ path: '.env.local' });

const transport = nodemailer.createTransport({
  host: 'smtp.sendgrid.net',
  port: 587,
  auth: {
    user: 'apikey',
    pass: process.env.SENDGRID_API_KEY,
  },
});

export const sendMail = buildSendMail({
  transport,
  defaultFrom: 'gatekeeper@gatekeep.it',
});
```

**Comment by neuxregime** [comment]
issue resolved with `forceDeliver`

```typescript
sendMail({
      subject: `Ready for 123?`,
      to: entry.email,
      component: mailTemplate,
      forceDeliver: true,
    });
```

**Comment by psugihara** [comment]
awesome, sorry I missed this @neuxregime.

Glad you figured it out (if `process.env.NODE_ENV !== "production"` then it will try to open in the preview server). Here's the bit or relevant logix: https://github.com/successor-software/mailing/blob/main/packages/core/src/index.ts#L60

lmk if you need any other help (or feel free to hit me up directly).

**Comment by neuxregime** [comment]
> awesome, sorry I missed this @neuxregime.
> 
> Glad you figured it out (if `process.env.NODE_ENV !== "production"` then it will try to open in the preview server). Here's the bit or relevant logix: https://github.com/successor-software/mailing/blob/main/packages/core/src/index.ts#L60
> 
> lmk if you need any other help (or feel free to hit me up directly).

Thank you for the response. I actually ended up in the same LOC when inspecting my issue!

**Comment by akdeb** [comment]
Any idea why this works with forceDeliver and not without it?

**Comment by psugihara** [comment]
That error shows when NODE_ENV is development to prevent you from accidentally sending in dev. forceDeliver skips this guard.
