### ISSUE TITLE
Running without importing React?

### ISSUE THREAD

**Issue by mrlubos** [successor-software/mailing#73]
Hey! Loving this project, this is exactly what I was after for a long time (https://github.com/wix-incubator/mjml-react/issues/37). I am playing around with the boilerplate and I discovered a few issues I will report in this project. The first one is whether it's possible to run this project without importing React? I copy-pasted my tsconfig from another project that supports this, but running `mailing preview` after removing all React imports throws this error

```
error TS2686: 'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.
```

**Comment by psugihara** [comment]
No, your project must have react imported for it to work. Mailing doesn't provide its own version because we imagined most people would be running this inside of a next.js app and running multiple versions of react at the same time can cause issues.

I like your idea in #75 and think we should generate the tsconfig + package.json with all necessary deps with that command so that users don't have to think about this.

**Comment by mrlubos** [comment]
Hey @psugihara, thanks for all your replies. Just to clear any potential confusion, I am asking if instead of the default boilerplate component like this

```tsx
// src/components/my-component.tsx

import React from 'react';

export function MyComponent() {
  return null;
}
```

I could simply write my components like this


```tsx
// src/components/my-component.tsx

export function MyComponent() {
  return null;
}
```

Next.js [seems to support this syntax](https://nextjs.org/docs/upgrading#react-16-to-17). Can you confirm if this is something I need to update in my configuration or it's on `mailing`'s side?

**Comment by psugihara** [comment]
Ah gotcha, thanks so much for clarifying. Yes, at the moment `mailing` requires React to be imported but I think it totally makes sense to support tsx and jsx files without it in the future like next does. In general I want next to have first-class support and this is a great example of something that will make dropping it into a next app simpler.

Now just need to figure out how to implement it :)
